package ir.ac.kntu.Meowter.util;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.List;

public class HtmlReportGeneratorUtil {

    private static final String REPORTS_PATH = "resources/reports/";

    public static String generateReport(String title, List<String> headers, List<List<String>> data) {
        File reportsDir = new File(REPORTS_PATH);
        if (!reportsDir.exists()) {
            if (!reportsDir.mkdirs()) {
                System.out.println("Failed to create reports directory!");
                return null;
            }
        }
        String fileName = REPORTS_PATH + title.replaceAll(" ", "_") + ".html";
        try (FileWriter writer = new FileWriter(fileName)) {
            writer.write("<!DOCTYPE html><html lang=\"en\"><head>");
            writer.write("<meta charset=\"UTF-8\">");
            writer.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            writer.write("<title>" + title + "</title>");
            writer.write("<style>");
            writer.write("body { font-family: Arial, sans-serif; margin: 20px; background-color: #f9f9f9; color: #333; }");
            writer.write("h1 { text-align: center; color: #4CAF50; }");
            writer.write("table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 1em; }");
            writer.write("th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }");
            writer.write("th { background-color: #4CAF50; color: white; }");
            writer.write("tr:nth-child(even) { background-color: #f2f2f2; }");
            writer.write("tr:hover { background-color: #ddd; }");
            writer.write(".footer { text-align: center; margin-top: 20px; font-size: 0.9em; color: #555; }");
            writer.write("</style>");
            writer.write("</head><body>");
            writer.write("<h1>" + title + "</h1>");
            writer.write("<table><thead><tr>");
            for (String header : headers) {
                writer.write("<th>" + header + "</th>");
            }
            writer.write("</tr></thead><tbody>");

            for (List<String> row : data) {
                writer.write("<tr>");
                for (String cell : row) {
                    writer.write("<td>" + cell + "</td>");
                }
                writer.write("</tr>");
            }
            writer.write("</tbody></table>");
            writer.write("<div class=\"footer\">Generated by Meowter Report Generator</div>");
            writer.write("</body></html>");
        } catch (IOException e) {
            System.out.println("Error generating report: " + e.getMessage());
        }
        return "file://" + Paths.get(fileName).toAbsolutePath().toString();
    }
}
